language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t aronp/multicontainer-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aronp/multicontainer-docker npm test

after_success: 
  - docker build -t aronp/multi-client ./client
  - docker build -t aronp/multi-nginx ./nginx
  - docker build -t aronp/multi-server ./server
  - docker build -t aronp/multi-worker ./worker 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aronp/multi-client
  - docker push aronp/multi-nginx
  - docker push aronp/multi-server
  - docker push aronp/multi-worker

deploy:
  provider: elastic-beanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-612258774112
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY